# Generated by Django 3.0.7 on 2020-08-04 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('genre', models.CharField(choices=[('action', 'action'), ('comedy', 'comedy'), ('romantic', 'romantic'), ('drama', 'drama'), ('sad', 'sad'), ('horror', 'horror')], max_length=20)),
                ('casts', models.CharField(max_length=200)),
                ('language', models.CharField(choices=[('en', 'ENGLISH'), ('sp', 'spanish')], max_length=200)),
                ('director', models.CharField(max_length=200)),
                ('release_date', models.DateField(auto_now_add=True)),
                ('length', models.IntegerField()),
                ('budget', models.IntegerField()),
            ],
        ),
    ]
