# Generated by Django 3.0.7 on 2020-08-04 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_movie_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='image',
            field=models.ImageField(default='', upload_to='movies'),
            preserve_default=False,
        ),
    ]
