# Generated by Django 3.0.7 on 2020-08-04 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_movie_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='release_date',
            new_name='update_time',
        ),
    ]
