# Generated by Django 3.0.7 on 2020-08-05 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_movie_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='language',
            field=models.CharField(choices=[('english', 'english'), ('spanish', 'spanish'), ('nepali', 'nepali')], max_length=200),
        ),
    ]
